### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by edraprasetio** [jakecomp/covid19-dashboard#4]
**Feature Request: Docker file**
Running the program with python3.10 causes a number of missing library errors when downloading dependencies. Below is a snapshot of the error message:
<img width="1009" alt="Screen Shot 2022-04-14 at 20 34 59" src="https://user-images.githubusercontent.com/67980359/163514633-690dc0cc-74fb-458d-b1fb-009fd2df1483.png">
**Task**
Create a docker container to resolve dependency issues

**Comment by edraprasetio** [comment]
What appears to be the case is that the program runs in python3.7. To avoid other users from having to switch from different python versions to python3.7, we create a container that runs in python3.7

**Comment by edraprasetio** [comment]
We then build a docker file and image that are able to containerize the program.
<img width="511" alt="Screen Shot 2022-04-14 at 20 51 12" src="https://user-images.githubusercontent.com/67980359/163515507-909745d2-63bb-4431-ae35-247c0026cf26.png">

<img width="1004" alt="Screen Shot 2022-04-14 at 20 58 12" src="https://user-images.githubusercontent.com/67980359/163516018-8aeab43f-ed6b-4c59-9bff-ef3944eaf650.png">

<img width="960" alt="Screen Shot 2022-04-14 at 20 58 21" src="https://user-images.githubusercontent.com/67980359/163516030-2723eab1-b7b5-4432-bbf8-1ac9038fc6dd.png">

As seen above, the docker allows the machine to download dependencies without any issues.

**Comment by jakecomp** [comment]
I ran the container myself Ed and it all looks good!
